// Import customers from customers_registration.json into PRODUCTION DB.
//
// Usage: node backend/scripts/import_customers_to_prod.mjs
//
// - Generates a single SQL file with all INSERTs inside BEGIN/COMMIT.
// - SCPs the SQL to the production server.
// - Executes it inside the prod Postgres container.
// - Forces preferred_currency='TRY' for every imported customer.
// - Keeps wallet_balances in their original currencies (EUR/TRY/USD).
// - ON CONFLICT (email) DO NOTHING — will not touch the 2 existing students.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import bcrypt from 'bcrypt';
import { NodeSSH } from 'node-ssh';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..', '..');

const JSON_PATH = path.join(repoRoot, 'customers_registration.json');
const SQL_OUT = path.join(repoRoot, 'prod_customers_import.sql');
const SECRETS_PATH = path.join(repoRoot, '.deploy.secrets.json');

const DEFAULT_PASSWORD = 'customer123';
const STUDENT_ROLE_NAME = 'student';
const REMOTE_DB_CONTAINER = 'plannivo_db_1';
const REMOTE_DB_USER = 'plannivo';
const REMOTE_DB_NAME = 'plannivo';
const REMOTE_TMP = '/tmp/prod_customers_import.sql';

function normEmail(e) {
  return (e || '').toLowerCase().trim();
}
function syntheticEmail(niceId) {
  return `customer-${niceId}@imported.local`;
}
function suffixEmail(email, niceId) {
  const at = email.indexOf('@');
  if (at < 0) return syntheticEmail(niceId);
  return `${email.slice(0, at)}+n${niceId}${email.slice(at)}`;
}
// Postgres string literal escape (single quotes doubled).
function q(s) {
  if (s === null || s === undefined) return 'NULL';
  return `'${String(s).replace(/'/g, "''")}'`;
}
function num(n) {
  if (n === null || n === undefined || !Number.isFinite(Number(n))) return 'NULL';
  return String(Number(n));
}

async function generateSql() {
  const customers = JSON.parse(fs.readFileSync(JSON_PATH, 'utf-8'));
  const passwordHash = await bcrypt.hash(DEFAULT_PASSWORD, 10);

  const taken = new Set();
  const rewrites = [];
  const rows = [];
  const walletEntries = []; // { email, currency, amount }
  let withNegative = 0;

  for (const c of customers) {
    const niceId = c.niceId;
    const rawEmail = normEmail(c.email);
    let email;
    if (!rawEmail) email = syntheticEmail(niceId);
    else if (taken.has(rawEmail)) {
      email = suffixEmail(rawEmail, niceId);
      rewrites.push({ niceId, original: rawEmail, rewritten: email });
    } else email = rawEmail;
    if (taken.has(email)) email = syntheticEmail(niceId);
    taken.add(email);

    const list = c.rawData?.customerBalanceDto?.customerCurrencySummaryDtoList || [];
    const positives = list.filter((s) => Number(s.balance) > 0);
    const negatives = list.filter((s) => Number(s.balance) < 0);

    for (const n of negatives) {
      if (n.currencyCode !== 'EUR') {
        throw new Error(
          `Customer niceId=${niceId} has a non-EUR negative balance in ${n.currencyCode}; legacy users.balance is EUR-only.`
        );
      }
    }
    const negativeEur = negatives.reduce((acc, n) => acc + Number(n.balance), 0);
    if (negativeEur < 0) withNegative++;

    const name =
      [c.firstName, c.lastName].filter(Boolean).join(' ').trim() || `Customer ${niceId}`;

    rows.push({
      name,
      email,
      firstName: c.firstName || null,
      lastName: c.lastName || null,
      phone: c.phone || null,
      country: c.country || null,
      age: Number.isFinite(c.age) && c.age > 0 ? c.age : null,
      weight: Number.isFinite(c.weight) && c.weight > 0 ? c.weight : null,
      balance: negativeEur < 0 ? negativeEur : 0,
      medicalNote: c.medicalNote || null,
    });

    for (const p of positives) {
      walletEntries.push({ email, currency: p.currencyCode, amount: Number(p.balance) });
    }
  }

  const lines = [];
  lines.push('-- Auto-generated by import_customers_to_prod.mjs');
  lines.push('-- DO NOT EDIT — regenerate from customers_registration.json');
  lines.push('SET client_min_messages = WARNING;');
  lines.push('BEGIN;');
  lines.push('');
  lines.push(`DO $$ DECLARE v_role_id uuid; BEGIN`);
  lines.push(`  SELECT id INTO v_role_id FROM roles WHERE name = ${q(STUDENT_ROLE_NAME)};`);
  lines.push(`  IF v_role_id IS NULL THEN RAISE EXCEPTION 'student role not found'; END IF;`);
  lines.push(`  PERFORM set_config('plannivo.student_role_id', v_role_id::text, true);`);
  lines.push(`END $$;`);
  lines.push('');
  lines.push('-- Insert customers (ON CONFLICT with active-email partial unique index)');

  for (const r of rows) {
    lines.push(
      `INSERT INTO users (name, email, password_hash, first_name, last_name, phone, country, age, weight, preferred_currency, role_id, balance, notes, registration_source)
 VALUES (${q(r.name)}, ${q(r.email)}, ${q(passwordHash)}, ${q(r.firstName)}, ${q(r.lastName)}, ${q(r.phone)}, ${q(r.country)}, ${num(r.age)}, ${num(r.weight)}, 'TRY', current_setting('plannivo.student_role_id')::uuid, ${num(r.balance)}, ${r.medicalNote ? q('Medical note: ' + r.medicalNote) : 'NULL'}, 'legacy_import')
 ON CONFLICT (email) WHERE deleted_at IS NULL DO NOTHING;`
    );
  }

  lines.push('');
  lines.push('-- Wallet balances (only for rows we just inserted — joined by email)');
  for (const w of walletEntries) {
    lines.push(
      `INSERT INTO wallet_balances (user_id, currency, available_amount)
 SELECT id, ${q(w.currency)}, ${num(w.amount)} FROM users WHERE email = ${q(w.email)} AND deleted_at IS NULL AND registration_source = 'legacy_import'
 ON CONFLICT (user_id, currency) DO UPDATE SET available_amount = EXCLUDED.available_amount, updated_at = now();`
    );
  }

  lines.push('');
  lines.push('COMMIT;');
  lines.push('');
  lines.push('-- Summary');
  lines.push(`SELECT COUNT(*) AS imported_customers FROM users WHERE registration_source = 'legacy_import';`);
  lines.push(`SELECT currency, COUNT(*) AS n, SUM(available_amount) AS total FROM wallet_balances wb JOIN users u ON u.id = wb.user_id WHERE u.registration_source = 'legacy_import' GROUP BY currency ORDER BY currency;`);
  lines.push(`SELECT COUNT(*) AS negative_balance_customers, COALESCE(SUM(balance),0) AS total_owed FROM users WHERE registration_source = 'legacy_import' AND balance < 0;`);

  fs.writeFileSync(SQL_OUT, lines.join('\n'), 'utf-8');
  console.log(`Wrote ${SQL_OUT}`);
  console.log(`  Customer INSERTs:     ${rows.length}`);
  console.log(`  Wallet balance rows:  ${walletEntries.length}`);
  console.log(`  Negative balances:    ${withNegative}`);
  console.log(`  Email rewrites:       ${rewrites.length}`);
  return { customerCount: rows.length, walletCount: walletEntries.length, rewrites };
}

async function deploy() {
  if (!fs.existsSync(SECRETS_PATH)) {
    throw new Error(`${SECRETS_PATH} not found — cannot SSH to production`);
  }
  const secrets = JSON.parse(fs.readFileSync(SECRETS_PATH, 'utf-8'));
  const ssh = new NodeSSH();
  console.log(`\nConnecting to ${secrets.host}...`);
  await ssh.connect({
    host: secrets.host,
    username: secrets.user || 'root',
    password: secrets.password,
    readyTimeout: 20000,
  });

  try {
    console.log('Uploading SQL...');
    await ssh.putFile(SQL_OUT, REMOTE_TMP);

    console.log('Copying SQL into the DB container...');
    const cp = await ssh.execCommand(
      `docker cp ${REMOTE_TMP} ${REMOTE_DB_CONTAINER}:${REMOTE_TMP}`
    );
    if (cp.code !== 0) throw new Error(`docker cp failed: ${cp.stderr}`);

    console.log('Executing inside production Postgres...');
    const psql = await ssh.execCommand(
      `docker exec ${REMOTE_DB_CONTAINER} psql -U ${REMOTE_DB_USER} -d ${REMOTE_DB_NAME} -v ON_ERROR_STOP=1 -f ${REMOTE_TMP}`
    );

    if (psql.stdout) console.log('\n--- psql stdout ---\n' + psql.stdout);
    if (psql.stderr) console.log('\n--- psql stderr ---\n' + psql.stderr);
    if (psql.code !== 0) throw new Error(`psql failed with exit code ${psql.code}`);

    console.log('\nCleaning up remote SQL file...');
    await ssh.execCommand(
      `rm -f ${REMOTE_TMP} && docker exec ${REMOTE_DB_CONTAINER} rm -f ${REMOTE_TMP}`
    );

    console.log('\n✓ Production import complete.');
    console.log(`  Default password for every imported customer: ${DEFAULT_PASSWORD}`);
  } finally {
    ssh.dispose();
  }
}

async function main() {
  await generateSql();
  await deploy();
}

main().catch((err) => {
  console.error('\nFATAL:', err.message);
  process.exit(1);
});
