-- Migration: 200_create_kai_tables
-- Purpose: Create tables for Kai AI assistant — session memory, instructor notes, and Google Doc tracking.
--          Replaces the n8n-managed kai_chat_memory table with an Express-managed session store.

-- ── Session Memory ─────────────────────────────────────────────────────────────
-- Stores conversation history per session. Session ID is generated by the frontend
-- and passed through the request chain. user_id is nullable to support guest sessions.
CREATE TABLE IF NOT EXISTS kai_sessions (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  TEXT        UNIQUE NOT NULL,
  user_id     UUID        REFERENCES users(id) ON DELETE SET NULL,
  user_role   TEXT        NOT NULL DEFAULT 'outsider',
  messages    JSONB       NOT NULL DEFAULT '[]',
  summary     TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kai_sessions_session_id ON kai_sessions (session_id);
CREATE INDEX IF NOT EXISTS idx_kai_sessions_user_id   ON kai_sessions (user_id);

-- ── Instructor Notes on Students ───────────────────────────────────────────────
-- instructor_id nullable so admin-authored notes are still valid.
CREATE TABLE IF NOT EXISTS kai_notes (
  id            SERIAL      PRIMARY KEY,
  student_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  instructor_id UUID        REFERENCES users(id) ON DELETE SET NULL,
  note_text     TEXT        NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kai_notes_student_id    ON kai_notes (student_id);
CREATE INDEX IF NOT EXISTS idx_kai_notes_instructor_id ON kai_notes (instructor_id);

-- ── Google Doc Tracking ────────────────────────────────────────────────────────
-- One row per student. n8n checks this before creating a new Doc to prevent duplicates.
-- All student note docs live in the shared Drive folder "UKC — Student Notes".
CREATE TABLE IF NOT EXISTS kai_student_docs (
  id              SERIAL      PRIMARY KEY,
  student_id      UUID        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  google_doc_id   TEXT        NOT NULL,
  google_doc_url  TEXT        NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
